version: '3.8'

services:
  lint:
    build:
      context: .
      dockerfile: DockerfileForDockerCompose
    image: ${TEXT_LINT_IMAGE_NAME}:${TEXT_LINT_IMAGE_TAG}
    volumes:
      - .:/workspaces/daigirin-tbf14
      - /workspaces/daigirin-tbf14/node_modules
    working_dir: /workspaces/daigirin-tbf14
    command: yarn lint
  build_theme:
    build:
      context: .
      dockerfile: DockerfileForDockerCompose
    image: ${SASS_IMAGE_NAME}:${SASS_IMAGE_TAG}
    volumes:
      - .:/workspaces/daigirin-tbf14
      - /workspaces/daigirin-tbf14/node_modules
    working_dir: /workspaces/daigirin-tbf14
    command: yarn build_theme
