name: Docker Image CI

on:
  push:
    branches:
      - main
  workflow_dispatch: ~

env:
  IMAGE: ghcr.io/yumemi/daigirin-tbf14

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login
        run: echo '${{ github.token }}' | docker login ghcr.io -u $ --password-stdin
      - name: Build & Push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ ENV.IMAGE }}:latest
